name: Deploy Nuxt SSR SPA

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build SSR Site
        run: bun run build
        env:
          ORIGIN: ${{ secrets.ORIGIN }}
          STRAPI_URL: ${{ secrets.STRAPI_URL }}
          NUXT_PUBLIC_RECAPTCHA_SITE_KEY: ${{ secrets.NUXT_PUBLIC_RECAPTCHA_SITE_KEY }}
          RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}
          FUEL_CARD_API_USERNAME: ${{ secrets.FUEL_CARD_API_USERNAME }}
          FUEL_CARD_API_PASSWORD: ${{ secrets.FUEL_CARD_API_PASSWORD }}
          FUEL_CARD_API_CUSTOMER_ID: ${{ secrets.FUEL_CARD_API_CUSTOMER_ID }}

      - name: Create .env file
        run: |
          echo "FUEL_CARD_API_USERNAME=${{ secrets.FUEL_CARD_API_USERNAME }}" >> .env
          echo "FUEL_CARD_API_PASSWORD=${{ secrets.FUEL_CARD_API_PASSWORD }}" >> .env
          echo "FUEL_CARD_API_CUSTOMER_ID=${{ secrets.FUEL_CARD_API_CUSTOMER_ID }}" >> .env
          echo "STRAPI_URL=${{ secrets.STRAPI_URL }}" >> .env
          echo "ORIGIN=${{ secrets.ORIGIN }}" >> .env

      - name: Copy files to Server (rsync)
        uses: easingthemes/ssh-deploy@v5.0.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlptzvi --delete"
          SOURCE: ".output/ .env ecosystem.config.js"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET_DIR }}
          EXCLUDE: "/dist/, /node_modules/"

      - name: Execute PM2 Commands (ssh-action)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -ex
            cd ${{ secrets.TARGET_DIR }}
            pm2 startOrReload ecosystem.config.js --update-env
            pm2 save